version: "3.9"

services:
  db:
    image: mysql:9.6
    container_name: snippetbox-db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SNIPPETBOX_DB_NAME}
      MYSQL_USER: ${SNIPPETBOX_DB_USER}
      MYSQL_PASSWORD: ${SNIPPETBOX_DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - snippetbox-db-data:/var/lib/mysql
    networks:
      - snippetbox-network  
    # This avoids some delays due to default MySQL 9.6 settings. 
    # command: ["--default-authentication-plugin=mysql_native_password"]
  

  app:
    build: .
    container_name: snippetbox-app
    restart: unless-stopped
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - snippetbox-network

networks:
  snippetbox-network:
    driver: bridge

volumes:
  snippetbox-db-data: 
